### ISSUE TITLE
NetSoakTest abruptly halts on Linux 

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de-netsoaktest#25] opened 2022-05-14 00:47 UTC
Built project for Linux

* Ran AP to process assets
* Attempted to launch NetSoakTest via `./build/linux/bin/profile/NetSoakTest.ServerLauncher  --soak_mode=loopback --rhi=null`
* Launcher fails on startup with:

```
Launcher: Connected to Asset Processor
AssetUtils: 
==================================================================
AssetUtils: Trace::Error
 /<path>/Dev/o3de/o3de/Gems/Atom/RPI/Code/Source/RPI.Reflect/Asset/AssetUtils.cpp(28): 'void AZ::RPI::AssetUtils::AssetUtilsInternal::ReportIssue(AZ::RPI::AssetUtils::TraceLevel, const char *)'
AssetUtils: Unable to find product asset 'shaders/sceneandviewsrgs.azshader'. Has the source asset finished building?
AssetUtils: ==================================================================
RPI system: 
==================================================================
RPI system: Trace::Error
 /<path>/Dev/o3de/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp(378): 'virtual void AZ::RPI::RPISystem::InitializeSystemAssets()'
RPI system: Failed to load RPI system asset shaders/sceneandviewsrgs.azshader
RPI system: ==================================================================
Logger: > sv_isDedicated : true
Launcher: Application is configured to use device local files at /<path>/Dev/o3de/o3de-netsoaktest/Cache/linux
Launcher: Log and cache files will be written to device storage
Module: Attempting to load module:/<path>/Dev/o3de/o3de-netsoaktest/build/linux/bin/profile/libCrySystem.so
Module: Success!
Aborted

```

Adding `-NullRenderer` did not stop application suddenly stopping

**Comment by junbo75** [comment] 2022-07-07 17:43
I will try to repro the issue today.

**Comment by junbo75** [comment] 2022-07-08 17:41
I cannot repro this issue with the latest engine (development@0a59f62) and project (development@8cff785). The server launcher is launched successfully. Screenshot and server log are attached.

![Screenshot from 2022-07-08 10-36-29](https://user-images.githubusercontent.com/68558268/178042961-eb27acab-acdb-4349-981a-5bda341f66eb.png)

[Server.log](https://github.com/o3de/o3de-netsoaktest/files/9074105/Server.log)

**Comment by junbo75** [comment] 2022-07-08 17:43
@lmbr-pip I think we can close this issue for now since it's not reproducible.

**Closed** 2022-08-11 17:35 UTC
Labels: kind/bug, sig/network
